### ISSUE TITLE
Limite des années de création d'entreprise

### ISSUE THREAD

**Issue by sylvainlb** [jmvanel/corporate_risk#10]
A quelle année doit-on limiter la date de création d'entreprise ?
On peut limiter à l'année en cours au maximum.

**Comment by djigodiabe** [comment]
Pour la limite de la date de création d'entreprise, on peut la limiter à l'année en cours au maximum.

**Comment by sylvainlb** [comment]
Ok, et la limite inférieure ? 1500 ?

**Comment by djigodiabe** [comment]
Il n'y a pas moyen de le remplir seulement ? Sinon 1000 ans me semblent corrects car je n'ai pas trouvé d'entreprise plus ancien que cette date. Après si tu penses  que 1500 ans soient plus appropriés, tu peux le mettre.

**Comment by sylvainlb** [comment]
Si on peut remplir et ne pas mettre de limite, comme c'est actuellement.

**Comment by djigodiabe** [comment]
Oui c'est mieux

**Comment by sylvainlb** [comment]
Ok donc je laisse tel quel
