### ISSUE TITLE
Remplacer les boutons SAVE par précédent et suivant

### ISSUE THREAD

**Issue by sylvainlb** [jmvanel/corporate_risk#14]

**Comment by sylvainlb** [comment]
@jmvanel, tel que je le vois, ça nécessite de supprimer les boutons existants et d'en créer des nouveaux à l'extérieur du formulaire. Seule l'application a connaissance de la séquence des formulaires, pas les formulaires eux-mêmes.

**Comment by sylvainlb** [comment]
Ou alors on peut aussi rendre les boutons configurables dans le formulaire, selon le boulot que ça représente @jmvanel

**Comment by jmvanel** [comment]
dans semantics_forms  le bouton SAVE est déjà configurable dans l'API, car l'URI relatif de l'action HTTP, par default /save , est un argument dans generateHTML() .

**Comment by sylvainlb** [comment]
Oui mais là on a besoin 2 deux boutons différents (précédent/suivant).

**Comment by jmvanel** [comment]
OK; donc là je vois 2 solutions:
- une option dans semantics_forms dans Form2HTML.generateHTML() pour enlever complètement le bouton , mais alors il faut un Id pour brancher un bouton de l'extérieur sur ce formulaire HTML, ou alors un pointeur à la DOM vers l'intérieur du XHTML si c'est possible;
- ou alors un nouvel argument dans Form2HTML.generateHTML() comme
  <code>actionURI: String = "/save" </code> ,  mais qui concerne le 2ème bouton, puisqu'il y en a déjà  2

**Comment by sylvainlb** [comment]
Fait, mais il faudrait pouvoir personnaliser les labels des boutons.
