### ISSUE TITLE
Demande de confirmation de sauvegarde des réponses 

### ISSUE THREAD

**Issue by sylvainlb** [jmvanel/corporate_risk#15]

**Comment by sylvainlb** [comment]
J'ai peur que ce soit un peu lourd pour l'utilisateur : beaucoup de clics de confirmation pour peu de clics de réponses

**Comment by djigodiabe** [comment]
On remplace cette partie par des flèches qui permettent de naviguer entre les questionnaires. Le fait de quitter le questionnaire enregistre automatiquement les réponses déjà remplies.
