### ISSUE TITLE
Mettre le contenu du rapport

### ISSUE THREAD

**Issue by sylvainlb** [jmvanel/corporate_risk#17]

**Comment by jmvanel** [comment]
Je dois écrire les requêtes SPARQL et ou le code pour obtenir les données brutes suivant l'API .

**Comment by jmvanel** [comment]
Duplique #30 .

**Comment by sylvainlb** [comment]
Cette issue-ci était plutôt pour le contenu alors que l'autre faisait référence au style, mais on peut tout regrouper, effectivement.
