### ISSUE TITLE
moyenne pour les questions capital 

### ISSUE THREAD

**Issue by jmvanel** [jmvanel/corporate_risk#21]
Les questions risque ont une réponse sous forme de numéro;
les questions capital ont une réponse sous forme de choix ( techniquement un owl:oneOf ).

Il faut leur affecter un numéro pour que la fonction de moyenne puisse les traiter.

**Comment by sylvainlb** [comment]
Pour #13 il faut aussi mettre les questions risque en owl:oneOf, non ?

**Comment by jmvanel** [comment]
On garde l'existant avec les numéros pour:
1. risque ( les libellés des réponses sont les même partout ; source de données tableur )
2. capital :  réponse sous forme de choix owl:oneOf

## Affichage des formulaires

D'abord voici au sujet de l'affichage des formulaires.
Pour 1 on a fait un petit développement spécifique dans semantic_forms pour présenter pour le datatype
http://www.bizinnov.com/ontologies/quest.owl.ttl#interval-1-5
( intervalle 0-5 ) la saisie sous forme de menu déroulant avec des libellés déclarés dans la base RDF.
Ce développement spécifique se trouve dans 
createHTMLiteralEditableField()
dans le trait deductions.runtime.html.Form2HTMLEdit .
Ca passe par le remplissage de possibleValuesMap dans la syntaxe abstraite de formulaire:

``` scala
  case class FormSyntax(
    // ...
    /** Map from property to possible Values  */
      val possibleValuesMap = scala.collection.mutable.Map[ NODE, Seq[(NODE, NODE)]]()
```

Pour 2, on est effectivement complétement dans la sémantique standard de owl:oneOf qui est la façon normale de représenter un choix exclusif. Il y a juste un point délicat, c'est que ici les choix sont des noeuds anonymes, pas des URI (dû à la génération de l'ontologie par un moteur de règles).

## Calculs de moyenne

Ensuite voici au sujet des calculs de moyenne.

Voici comment on leur affecte un numéro pour que la fonction de moyenne puisse les traiter.
Ca commence par la génération des données à partir du MarkDown. Chaque élément de la liste owl:oneOf reçoit un numéro d'ordre:

``` turtle
ques:capital-10
    a owl:ObjectProperty ;
    rdfs:comment "Veuillez sélectionner une seule des propositions suivantes :" ;
    rdfs:domain ques:capital-9 ;
    rdfs:label "Sport, Culture, loisirs" ;
    rdfs:range [
        owl:oneOf ([
                ques:value 1 ;
                rdfs:label """ Toutes les régions d’implantation de l’entreprise sont très pauvres
sur le plan sportif, culturel ou des loisirs"""
            ]
            # etc ...
```

Ensuite les triplets avec ques:value sont utilisés par une requête SPARQL dans la fonction
averagePerForm dans ResponseAnalysis.scala .
