### ISSUE TITLE
Taille des listes déroulantes Diagnostique

### ISSUE THREAD

**Issue by sylvainlb** [jmvanel/corporate_risk#37]
Diagnostique : les menus déroulant des réponses au QCM ne sont pas assez larges. Il faudrait les remettre à l'image des menus déroulants du prédiag

**Comment by sylvainlb** [comment]
C'est un bug de semantic forms. Pour une raison qui m'échappe une classe xs est ajoutée au div contenant l'input.

**Comment by jmvanel** [comment]
En fait les CSS sont tous réglables dans Application.scala .

Pour info, dans SF semantic_forms les champs prédiag et diag ne sont pas faits dans le même code; car prédiag est une valeur numérique, dans createHTMLiteralEditableField() , et diag. est une valeur URI (énuméré + précisément ) , dans createHTMLResourceEditableField() .

**Comment by jmvanel** [comment]
Corrigé dans https://github.com/jmvanel/corporate_risk/commit/a3e895e93248237e1542fce4f9c9017a2957c9fa
