### ISSUE TITLE
Issue de la V1

### ISSUE THREAD

**Issue by djigodiabe** [jmvanel/corporate_risk#7]
Page Profil

Une fois l'entreprise créée le bouton "entrer" ne renvoie pas sur la page suivante
Le bouton "L'entreprise fait partie d'un groupe" ne marche pas
Année de création mettre les années (je vois avec morgane)

Page de Prédiag:

Enlever "Diagnostic" et le remplacer par "Prédiag"
Afficher le nbre de questions remplit sur le nbre de questions total
Dans le formulaire, quand on clique n'importe où sur la ligne des notes, on a une note égale à zéro qui est coché
Enlever les boutons "SAVE" et mettre des flèches qui permettent de naviguer entre les formulaires
Quand on quitte le formulaire, il faut qu'on ait une demande "Voulez-vous enregistrer vos réponses"
Quand on appuie sur "SAVE" on revient toujours à la page d'accueil
Mettre un texte expliquant la notation de 0 à 5 (niveau de maturité), il est dans le tableau excel
Page Diag:

Supprimer les lignes correspondant à "Question remplie" en trop
En appuyant sur "SAVE" on revient toujours à la page d'accueil
Enlever les boutons "SAVE" et mettre des flèches qui permettent de naviguer entre les formulaires
Quand on quitte le formulaire, il faut qu'on ait une demande "Voulez-vous enregistrer vos réponses"

Rapport: le rapport ne marche pas ni pour le prédiag ni pour le diag

Contact:

le bouton contact marche mais les logos "Demande de renseignement" et "Vous faire rappeler par nos experts" ne marchent pas. Je vais vous envoyer les coordonnées à mettre.
La page nous demande de nous connecter alors que nous le sommes déjà

**Comment by sylvainlb** [comment]
Je ferme, car j'ai mis tous les points dans des rapports uniques.

**Comment by djigodiabe** [comment]
Pour commencer, nous voudrions aussi changer le nom du logiciel VSI par ESI puis rajouter à côté du logo (Evaluation et Sécurisation du capital immatériel).
• Texte page connexion: 

L'outil E.S.I permet de mesurer et de piloter simplement les actifs immatériels de votre organisation.

-Pour la page de connexion, quand on met un mot de passe incorrect le logiciel ne nous le signale pas.  On aimerait aussi que le logo de l'observatoire de l'immatériel soit plus gros de manière à être plus visible. 

-Il faudrait remplacer le logo "DGCIS devient DGE" (logo que je vous ai fourni par mail)

-Dans le rapport, il faut mettre l'intitulé des items car elle ne s'affiche pas.

-Nous avons encore des champs qui s'affichent dans la partie "Diagnostic" qui ne devrait pas y être. Il s'agit des champs "Flexibilité",  "Fidélité", "Identification de l'entreprise".  

-Pour le pré-diag, si la note est inférieure à 3 qu'on ne puisse pas avoir accès au diag.  

-Au niveau du rapport concernant le graphique "gestion du capital immatériel", la légende ne s'affiche pas. Le tableau comporte plus de barre que d'item immatériel.

-Nous voulions savoir comment vous avez prévu l'affichage pour les entreprises qui ont fait plusieurs évaluations dans le temps pour une seule et même entreprise. Par exemple avoir l'évaluation de l'entreprise X pour le mois de janvier et celui du mois d'Avril par exemple de manière à pouvoir voir l'évolution de sa note du capital immatériel.

-Nous voulons que "version beta" soit affiché dans E.S.I
